# Generated by Django 4.0 on 2022-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='available',
        ),
        migrations.AddField(
            model_name='items',
            name='count_available',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='count available'),
        ),
    ]
