# Generated by Django 4.0 on 2022-01-12 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_items_available_items_count_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.RemoveField(
            model_name='books',
            name='cover',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(to='books.Categories'),
        ),
        migrations.AddField(
            model_name='items',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='items/photo/', verbose_name='cover'),
        ),
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.items')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='magazine number')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.languages', verbose_name='language')),
            ],
            options={
                'verbose_name': 'magazine',
                'verbose_name_plural': 'magazines',
            },
            bases=('books.items',),
        ),
        migrations.CreateModel(
            name='Figures',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.items')),
                ('character', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.brands')),
            ],
            options={
                'verbose_name': 'figure',
                'verbose_name_plural': 'figures',
            },
            bases=('books.items',),
        ),
    ]
