# Generated by Django 4.0 on 2022-01-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_brands_remove_books_category_remove_books_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(blank=True, to='books.Categories'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
