# Generated by Django 4.0 on 2022-01-13 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Оплачен', 'Оплачен'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Отменен', 'Отменен')], default='Ожидает оплаты', max_length=30, verbose_name='status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('status_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='status updated')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('date_from', models.DateField(default=django.utils.timezone.now, verbose_name='Date from')),
                ('date_to', models.DateField(verbose_name='Date to')),
                ('daily_payment', models.PositiveSmallIntegerField(default=50, help_text='Daily payment', verbose_name='daily payment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.invoice', verbose_name='invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'rent',
                'verbose_name_plural': 'rents',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.invoice', verbose_name='invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
            },
        ),
    ]
