# Generated by Django 4.0 on 2022-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('Оплачен', 'Оплачен'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Отменен', 'Отменен')], default='Ожидает оплаты', max_length=30, verbose_name='status'),
        ),
    ]
