# Generated by Django 4.0 on 2022-01-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_invoices_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statuses',
        ),
    ]
