# Generated by Django 4.0 on 2022-01-13 08:17
import csv

from django.db import migrations


def upload_regions(apps, schema_editor):
    Region = apps.get_model('accounts', 'Region')
    db_alias = schema_editor.connection.alias
    Region.import_from_csv('accounts/region.csv')


def delete_regions(apps, schema_editor):
    Region = apps.get_model('accounts', 'Region')
    db_alias = schema_editor.connection.alias
    Region.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(upload_regions, delete_regions),
    ]
