# Generated by Django 4.0 on 2022-01-10 10:02
import csv

from django.db import migrations


def upload_regions(apps, schema_editor):
    Regions = apps.get_model('accounts', 'Regions')
    db_alias = schema_editor.connection.alias
    with open('accounts/region.csv') as file:
        reader = csv.reader(file)
        for row in reader:
            Regions(region=row[2], country='Россия').save()


def delete_regions(apps, schema_editor):
    Regions = apps.get_model('accounts', 'Regions')
    db_alias = schema_editor.connection.alias
    Regions.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(upload_regions, delete_regions),
    ]
