# Generated by Django 4.0 on 2022-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('region',), 'verbose_name': 'region', 'verbose_name_plural': 'regions'},
        ),
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
