# Generated by Django 4.0 on 2022-01-13 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='author')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='books/authors_photo', verbose_name="author's photo")),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('count_available', models.PositiveSmallIntegerField(default=0, verbose_name='count available')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/photo/', verbose_name='photo')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category', models.ManyToManyField(blank=True, to='items.Category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='publisher')),
                ('address', models.TextField(verbose_name='address')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='magazine number')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.language', verbose_name='language')),
            ],
            options={
                'verbose_name': 'magazine',
                'verbose_name_plural': 'magazines',
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('character', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.brand')),
            ],
            options={
                'verbose_name': 'figure',
                'verbose_name_plural': 'figures',
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('year', models.DateField(verbose_name='year')),
                ('author', models.ManyToManyField(to='items.Author')),
                ('genre', models.ManyToManyField(to='items.Genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.language', verbose_name='language')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.publisher', verbose_name='publisher')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
            bases=('items.item',),
        ),
    ]
